CREATE TABLE RPG_USER 
(
    U_ID INT,
    U_FIRSTNAME VARCHAR2(4000) NOT NULL,
    U_LASTNAME VARCHAR2(4000) NOT NULL,
    U_USERNAME VARCHAR2(4000) UNIQUE NOT NULL,
    U_PASSWORD VARCHAR2(4000) NOT NULL,
    U_EMAIL VARCHAR2(4000) NOT NULL,
    OC_ID INT,
    PRIMARY KEY(U_ID)
);

CREATE SEQUENCE user_seq START WITH 1 INCREMENT BY 1;
  
CREATE OR REPLACE TRIGGER user_seq_trg BEFORE
  INSERT ON RPG_USER FOR EACH ROW BEGIN IF :new.u_id IS NULL THEN
  SELECT user_seq.NEXTVAL INTO :new.u_id FROM dual;
END IF;
END;
/  
    
    
    
CREATE TABLE OWN_CHARACTER(
  OC_ID INT,
  C_ID INT,
  U_ID INT,
  PRIMARY KEY(OC_ID)
);

CREATE TABLE CHAMPIONS(
  C_ID INT,
  C_NAME VARCHAR2(4000),
  C_HP NUMBER(36,2),
  C_MANA NUMBER(36,2),
  C_ATK NUMBER(36,2),
  C_DEF NUMBER(36,2),
  C_AS NUMBER(36,2),
  C_HIT NUMBER(36,2),
  C_FLEE NUMBER(36,2),
  C_CRIT NUMBER(36,2),
  C_DCRIT NUMBER(36,2),
  PRIMARY KEY(C_ID)
);

CREATE TABLE OWN_CHARACTER_EQUIPMENT(
  OCE_ID INT,
  OC_ID INT,
  HG_ID INT,
  AM_ID INT,
  GM_ID INT,
  WL_ID INT,
  WR_ID INT,
  FG_ID INT,
  AL_ID INT,
  AR_ID INT,
  PRIMARY KEY(OCE_ID)
)

CREATE TABLE HEADGEARS(
  HG_ID INT,
  HG_HP NUMBER(36,2),
  HG_MANA NUMBER(36,2),
  HG_ATK NUMBER(36,2),
  HG_DEF NUMBER(36,2),
  HG_AS NUMBER(36,2),
  HG_HIT NUMBER(36,2),
  HG_FLEE NUMBER(36,2),
  HG_CRIT NUMBER(36,2),
  HG_DCRIT NUMBER(36,2),
  PRIMARY KEY(H_ID)
);

CREATE TABLE ARMORS(
  AM_ID INT,
  AM_HP NUMBER(36,2),
  AM_MANA NUMBER(36,2),
  AM_ATK NUMBER(36,2),
  AM_DEF NUMBER(36,2),
  AM_AS NUMBER(36,2),
  AM_HIT NUMBER(36,2),
  AM_FLEE NUMBER(36,2),
  AM_CRIT NUMBER(36,2),
  AM_DCRIT NUMBER(36,2),
  PRIMARY KEY(AM_ID)
);

CREATE TABLE GARMENTS(
  GM_ID INT,
  GM_HP NUMBER(36,2),
  GM_MANA NUMBER(36,2),
  GM_ATK NUMBER(36,2),
  GM_DEF NUMBER(36,2),
  GM_AS NUMBER(36,2),
  GM_HIT NUMBER(36,2),
  GM_FLEE NUMBER(36,2),
  GM_CRIT NUMBER(36,2),
  GM_DCRIT NUMBER(36,2),
  PRIMARY KEY(GM_ID)
);


CREATE TABLE WEAPONSL(
  WL_ID INT,
  WL_HP NUMBER(36,2),
  WL_MANA NUMBER(36,2),
  WL_ATK NUMBER(36,2),
  WL_DEF NUMBER(36,2),
  WL_AS NUMBER(36,2),
  WL_HIT NUMBER(36,2),
  WL_FLEE NUMBER(36,2),
  WL_CRIT NUMBER(36,2),
  WL_DCRIT NUMBER(36,2),
  PRIMARY KEY(WL_ID)
);

CREATE TABLE WEAPONSR(
  WR_ID INT,
  WR_HP NUMBER(36,2),
  WR_MANA NUMBER(36,2),
  WR_ATK NUMBER(36,2),
  WR_DEF NUMBER(36,2),
  WR_AS NUMBER(36,2),
  WR_HIT NUMBER(36,2),
  WR_FLEE NUMBER(36,2),
  WR_CRIT NUMBER(36,2),
  WR_DCRIT NUMBER(36,2),
  PRIMARY KEY(WR_ID)
);

CREATE TABLE FOOTGEAR(
  FG_ID INT,
  FG_HP NUMBER(36,2),
  FG_MANA NUMBER(36,2),
  FG_ATK NUMBER(36,2),
  FG_DEF NUMBER(36,2),
  FG_AS NUMBER(36,2),
  FG_HIT NUMBER(36,2),
  FG_FLEE NUMBER(36,2),
  FG_CRIT NUMBER(36,2),
  FG_DCRIT NUMBER(36,2),
  PRIMARY KEY(FG_ID)
);

CREATE TABLE ACCESSORIESL(
  AL_ID INT,
  AL_HP NUMBER(36,2),
  AL_MANA NUMBER(36,2),
  AL_ATK NUMBER(36,2),
  AL_DEF NUMBER(36,2),
  AL_AS NUMBER(36,2),
  AL_HIT NUMBER(36,2),
  AL_FLEE NUMBER(36,2),
  AL_CRIT NUMBER(36,2),
  AL_DCRIT NUMBER(36,2),
  PRIMARY KEY(AL_ID)
);

CREATE TABLE ACCESSORIESR(
  AR_ID INT,
  AR_HP NUMBER(36,2),
  AR_MANA NUMBER(36,2),
  AR_ATK NUMBER(36,2),
  AR_DEF NUMBER(36,2),
  AR_AS NUMBER(36,2),
  AR_HIT NUMBER(36,2),
  AR_FLEE NUMBER(36,2),
  AR_CRIT NUMBER(36,2),
  AR_DCRIT NUMBER(36,2),
  PRIMARY KEY(AL_ID)
);